name: Pull latest on server (pll-app.asc-nest.org)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Trust host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Pull + Laravel maintenance
        env:
          PHP_BIN: ${{ secrets.PHP_BIN }}
        run: |
          ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} << 'EOF'
          set -e
          cd "${PROD_REMOTE_PATH:-/home/jhtewsbw2mz0/public_html/pll-app.asc-nest.org}"

          git fetch origin main
          git reset --hard origin/main
          git clean -fdx \
            -e storage \
            -e vendor \
            -e .env \
            -e cgi-bin \
            -e public/.well-known

          if [ -f composer.phar ]; then
            ${PHP_BIN:-/usr/local/bin/php} composer.phar install --no-dev --prefer-dist --optimize-autoloader
          elif command -v composer >/dev/null 2>&1; then
            composer install --no-dev --prefer-dist --optimize-autoloader
          fi

          ${PHP_BIN:-/usr/local/bin/php} artisan migrate --force || true
          ${PHP_BIN:-/usr/local/bin/php} artisan config:cache
          ${PHP_BIN:-/usr/local/bin/php} artisan route:cache
          EOF
